version: "3.9"
services:
  mysql:
    image: mysql:5.7
    healthcheck:
      test: mysqladmin ping -plocal_password
    environment:
      MYSQL_DATABASE: cockpit
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: local_password
    ports:
      - "3306:3306"
    networks:
      - db

networks:
  db: